FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
ENV DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
ENV DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}

CMD ["n8n", "start"]
